[package]
name = "aptos-rocksdb"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.22.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
bcs = "0.1.6"
anyhow = "1.0.93"
dotenv = "0.15.0"